apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kongair
  labels:
    app: kongair-experience-deployment
  name: kongair-experience
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kongair-experience
  template:
    metadata:
      labels:
        app: kongair-experience
    spec:
      containers:
      - image: kongedu/kongair-experience
        name: kongair-experience-deployment
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
status: {}
