apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kongair
  labels:
    app: kongair-routes-deployment
  name: kongair-routes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kongair-routes
  template:
    metadata:
      labels:
        app: kongair-routes
    spec:
      containers:
      - image: kongedu/kongair-routes
        name: kongair-routes-deployment
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
status: {}
